import { CarBrands } from '../../typings/enums/CarBrands';

const carBrands: CarBrands = [
    { id: 1, name: 'Abarth'},
    { id: 2, name: 'Alfa Romeo'},
    { id: 3, name: 'Aston Martin'},
    { id: 4, name: 'Audi'},
    { id: 5, name: 'Bentley'},
    { id: 6, name: 'BMW'},
    { id: 7, name: 'Buggati'},
    { id: 8, name: 'Cadillac'},
    { id: 9, name: 'Chevrolet'},
    { id: 10, name: 'Chrysler'},
    { id: 11, name: 'Citroen'},
    { id: 12, name: 'Dacia'},
    { id: 13, name: 'Daewoo'},
    { id: 14, name: 'Daihatsu'},
    { id: 15, name: 'Dodge'},
    { id: 16, name: 'Ferrari'},
    { id: 17, name: 'Fiat'},
    { id: 18, name: 'Ford'},
    { id: 19, name: 'FSM'},
    { id: 20, name: 'Honda'},
    { id: 21, name: 'Hummer'},
    { id: 22, name: 'Hyundai'},
    { id: 23, name: 'Infiniti'},
    { id: 24, name: 'Jaguar'},
    { id: 25, name: 'Jeep'},
    { id: 26, name: 'KIA'},
    { id: 27, name: 'Koenigsegg'},
    { id: 28, name: 'Lada'},
    { id: 29, name: 'Lamborghini'},
    { id: 30, name: 'Lancia'},
    { id: 31, name: 'Land Rover'},
    { id: 32, name: 'Lexus'},
    { id: 33, name: 'Lincoln'},
    { id: 34, name: 'Lotus'},
    { id: 35, name: 'Maserati'},
    { id: 36, name: 'Maybach'},
    { id: 37, name: 'Mazda'},
    { id: 38, name: 'Mclaren'},
    { id: 39, name: 'Mercedes'},
    { id: 40, name: 'Mini'},
    { id: 41, name: 'Mitsubishi'},
    { id: 42, name: 'Nissan'},
    { id: 43, name: 'Opel'},
    { id: 44, name: 'Peugeot'},
    { id: 45, name: 'FSO'},
    { id: 46, name: 'Porsche'},
    { id: 47, name: 'Renault'},
    { id: 48, name: 'Rolls Royce'},
    { id: 49, name: 'Rover'},
    { id: 50, name: 'Saab'},
    { id: 51, name: 'Seat'},
    { id: 52, name: 'Skoda'},
    { id: 53, name: 'Smart'},
    { id: 54, name: 'SsangYong'},
    { id: 55, name: 'Subaru'},
    { id: 56, name: 'Suzuki'},
    { id: 57, name: 'Tata'},
    { id: 58, name: 'Toyota'},
    { id: 59, name: 'Trabant'},
    { id: 60, name: 'Uaz'},
    { id: 61, name: 'Volkswagen'},
    { id: 62, name: 'Volvo'},
    { id: 63, name: 'Wartburg'},
];

export default carBrands;